POST http://localhost:3003/api/blogs/68cd25524123e0f48e927638/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4ODNjYmE4NzgyM2FjZjEwZTA3ZTk5NSIsImlhdCI6MTc1NDMwNjYyMX0.aeMEUF1Q3o00YkUL9En23Kk6oO5-4LAbEGbpjEAz9qk

{
  "comment": "Nice blog"
}